name: generate-json

# Controls when the action will run.
on: [push]

jobs: 
  generate-json:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout with branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      # Install ibmcloud cli and set ibmcloud api (target can be set with 'ibmcloud target -o <value> -s <value>' as well)
      - name: ibmcloud installation
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud login -u ${{ secrets.IBMCLOUD_USERNAME }} -p ${{ secrets.IBMCLOUD_PASSWORD }} -r ${{ secrets.IBMCLOUD_REGION }}
          ibmcloud target --cf
      
      # Install openwhisk
      - name: openwhisk installation
        run: |
          ibmcloud plugin install Cloud-Functions
      
      # Read the payload.json file (Change the path if you need to apply your own payload.json)
      - name: Read payload.json
        uses: microsoft/variable-substitution@v1
        with:
          files: 'payload.json'
        env:
          aws_access_key_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      # Create the alarm trigger with openwhisk #
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./payload.json
          
      - name: Echo payload.json
        run: echo "${{ steps.package.outputs.content }}"
