name: generate-json

# Controls when the action will run.
on:
  push:
    paths:
      - '**.json'

jobs: 
  generate-json:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout with branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Install ibmcloud cli and set ibmcloud api (target can be set with 'ibmcloud target -o <value> -s <value>' as well)
      - name: ibmcloud installation
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud login -u ${{ secrets.IBMCLOUD_USERNAME }} -p ${{ secrets.IBMCLOUD_PASSWORD }} -r ${{ secrets.IBMCLOUD_REGION }}
          ibmcloud target --cf
      
      # Install openwhisk and openwhisk-package-alarms library
      - name: openwhisk installation
        run: |
          ibmcloud plugin install Cloud-Functions
          ibmcloud wsk package get /whisk.system/alarms --summary
      
      # Find the new added json file
      - name: find added json
        id: added-files
        uses: tj-actions/changed-files@v17.2
      
      - name: List all added files
        run: |
          for file in ${{ steps.added-files.outputs.added_files }}; do
            filetype=".json"
            filename=${file//$filetype/}
            echo "alarm_name=$filename" >> $GITHUB_ENV
          done
      
      # Read payload.json
      - name: JSON to variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: '${{ env.alarm_name }}.json'
      
      # Set openwhisk alarm and rule
      - name: Create openwhisk alarm
        run: |
          ibmcloud wsk trigger create ${{ env.alarm_name }} --feed /whisk.system/alarms/alarm --param cron "0 */1 * * *"  --param trigger_payload "{\"forecast_code\":\"${{ env.json_forecast_code}}\",\"config_set\":\"${{ env.json_config_set}}\",\"function\":\"${{ env.json_function}}\",\"use_https\":\"${{ env.json_use_https}}\",\"aws_default_region\":\"${{ env.json_aws_default_region}}\",\"aws_s3_endpoint\":\"${{ env.json_aws_s3_endpoint}}\",\"aws_access_key_ID\":\"${{ secrets.AWS_ACCESS_KEY_ID}}\",\"aws_secret_access_key\":\"${{ secrets.AWS_SECRET_ACCESS_KEY}}\"}"
          ibmcloud wsk rule create ${{ env.alarm_name }}_rule ${{ env.alarm_name }} temp_seq
    
