name: generate-json

# Controls when the action will run.
on: [push]

jobs: 
  generate-json:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout with branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      # Install ibmcloud cli and set ibmcloud api (target can be set with 'ibmcloud target -o <value> -s <value>' as well)
      - name: ibmcloud installation
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud login -u ${{ secrets.IBMCLOUD_USERNAME }} -p ${{ secrets.IBMCLOUD_PASSWORD }} -r ${{ secrets.IBMCLOUD_REGION }}
          ibmcloud target --cf
      
      # Install openwhisk and openwhisk-package-alarms library
      - name: openwhisk installation
        run: |
          ibmcloud plugin install Cloud-Functions
          ibmcloud wsk package get /whisk.system/alarms --summary
      
      # Modify payload.json (Change the path if you need to apply your own payload.json)
      - name: Add the secret variables into payload.json
        uses: microsoft/variable-substitution@v1
        with:
          files: 'payload.json'
        env:
          aws_access_key_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      
      - name: JSON to variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'payload.json'
      - name: Show output
        run: echo "{\"forecast_code\":\"${{ env.json_forecast_code}}\"}"
    
